### ISSUE TITLE
Option for using 'Zero' instead of 'No' when zero cents in the amount

### ISSUE THREAD

**Issue by mecp** [Edditoria/numbo#1]
Not sure if issue is right place to discuss a feature request. Would it be possible to add an option for specifiying what word to use for zero cents. currently 'No' is used, but would be helpful if it could be made as option to allow other possible values like `Zero`.

**Comment by Edditoria** [comment]
Yes. Will do it in next release. Thanks for suggestion.

And this is a good place to discuss feature requests. One topic is one issue. 😄

**Comment by mecp** [comment]
Hey @Edditoria, thanks. looking forward to it.

**Comment by Edditoria** [comment]
Hi @mecp , the option is "drafted" as v2.5.0 (commit: 2f18faff80d88def24c76198542d8d41d2d5ad9a )

You can use it by:

```js
numbo.convert(123, 'enUS', 'chq', 'zeroCent');
// "One Hundred Twenty-three Dollars and Zero Cent Only"
```

In future releases, there will be a tool called "parseOption()" to handle all goodies.

Same as before, you can pass the options in any order. The "zeroCent" is only available for "enUS". Please enjoy.

In the meantime, you will need to pass the argument `'zeroCent'` every time. Is it better for you if you setup the properties while you declare the numbo object? i.e.:

```js
var numbo = new numbo({
  locale: 'enUS', zeroCent: true, withoutHyphen: true // pre-set the options as default
});
numbo.convert(123, 'chq') // "One Hundred Twenty Three Dollars and Zero Cent Only"
```

**Comment by mecp** [comment]
Hi @Edditoria

Thanks for the awesome speed to work on this enhancement.

> Is it better for you if you setup the properties while you declare the numbo object?

I don't really have a preference for it, specifying with each call is totally okay.

**Comment by mecp** [comment]
Hi @Edditoria 

I was wondering, when would you be publishing version `2.5.0` to npm?

**Comment by mecp** [comment]
Hi @Edditoria, waiting for the publishing of `2.5.0` release to npm.

**Comment by Edditoria** [comment]
Hi, very sorry about this. I have publish it to npm. And also "move" the tag `v2.5.0` to the latest commit.

Happy coding!

**Comment by mecp** [comment]
hey @Edditoria, thanks for that.
